services:

  ros2:

    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: auv_ros2_dev

    volumes:
      - .:/workspace

    working_dir: /workspace

    environment:
      - DISPLAY=${DISPLAY}

    stdin_open: true
    tty: true

    command: bash -c "cd /workspace && bash"
